import { useEffect, useState } from "react";
import "./styles/globals.css";

import ParticleCanvas from "./components/ParticleCanvas";
import AuthScreen from "./components/AuthScreen";

import UploadTab from "./tabs/UploadTab";
import AnswersTab from "./tabs/AnswersTab";
import ExportTab from "./tabs/ExportTab";

import { callClaude, loadState, saveState } from "./lib/api";
import { parseQuestions } from "./lib/parser";
import { SEED_DOCUMENTS, SEED_QUESTIONNAIRE } from "./lib/db";

export default function App() {
  // ── Auth ──────────────────────────────────────────────────────────────────
  const [user, setUser] = useState(() => {
    const raw = localStorage.getItem("medivault_user");
    return raw ? JSON.parse(raw) : null;
  });

  // ── Tab routing ───────────────────────────────────────────────────────────
  const [tab, setTab] = useState("upload");

  // ── Questionnaire state ───────────────────────────────────────────────────
  const [documents, setDocuments] = useState([...SEED_DOCUMENTS]);
  const [qText, setQText] = useState("");
  const [qName, setQName] = useState("Northshore Security Assessment");
  const [answers, setAnswers] = useState([]);
  const [generating, setGenerating] = useState(false);
  const [progress, setProgress] = useState({ cur: 0, total: 0 });
  const [hydrated, setHydrated] = useState(false);

  // ── Derived stats ─────────────────────────────────────────────────────────
  const answered = answers.filter(a => a.found).length;
  const notFound  = answers.filter(a => !a.found).length;
  const avgConf   = answers.length
    ? Math.round(answers.reduce((s, a) => s + a.confidence, 0) / answers.length)
    : 0;

  useEffect(() => {
    if (!user) {
      setHydrated(false);
      return;
    }

    localStorage.setItem("medivault_user", JSON.stringify(user));
    let active = true;

    loadState(user.id)
      .then((state) => {
        if (!active) return;
        setDocuments(state.documents?.length ? state.documents : [...SEED_DOCUMENTS]);
        setQText(state.qText || "");
        setQName(state.qName || "Northshore Security Assessment");
        setAnswers(state.answers || []);
      })
      .catch(() => {
        if (!active) return;
        setDocuments([...SEED_DOCUMENTS]);
        setQText("");
        setQName("Northshore Security Assessment");
        setAnswers([]);
      })
      .finally(() => {
        if (active) setHydrated(true);
      });

    return () => {
      active = false;
    };
  }, [user]);

  useEffect(() => {
    if (!user || !hydrated || generating) return;
    const timer = setTimeout(() => {
      saveState({
        userId: user.id,
        qName,
        qText,
        documents,
        answers,
      }).catch(() => {});
    }, 350);
    return () => clearTimeout(timer);
  }, [user, hydrated, generating, qName, qText, documents, answers]);

  // ── Actions ───────────────────────────────────────────────────────────────
  const generate = async () => {
    const text = qText || SEED_QUESTIONNAIRE;
    const qs = parseQuestions(text);
    if (!qs.length) { alert("No numbered questions found."); return; }

    setAnswers([]);
    setGenerating(true);
    setProgress({ cur: 0, total: qs.length });
    setTab("answers");

    const results = [];
    let errorCount = 0;
    try {
      for (let i = 0; i < qs.length; i++) {
        setProgress({ cur: i + 1, total: qs.length });
        try {
          const r = await callClaude(qs[i].text, documents);
          results.push({ number: qs[i].number, question: qs[i].text, ...r });
        } catch {
          // Keep generation moving even if one API call fails.
          results.push({
            number: qs[i].number,
            question: qs[i].text,
            answer: "Not found in references.",
            citations: [],
            confidence: 0,
            evidence: "",
            found: false,
          });
          errorCount += 1;
        }
        setAnswers([...results]);
      }
      if (errorCount === qs.length) {
        alert("All answer-generation requests failed. Please retry with valid reference documents.");
      }
    } finally {
      setGenerating(false);
    }
  };

  const editAnswer = (i, val) =>
    setAnswers(prev => prev.map((a, idx) => idx === i ? { ...a, answer: val } : a));

  const exportDoc = () => {
    let out = `${qName.toUpperCase()}\nGenerated by MediVault QA Tool — ${new Date().toLocaleDateString()}\n${"=".repeat(60)}\n\n`;
    answers.forEach(a => {
      out += `Q${a.number}. ${a.question}\n\nAnswer: ${a.answer}\n\n`;
      if (a.found && a.citations?.length) {
        out += `Citations:\n`;
        a.citations.forEach(c => out += `  • ${c}\n`);
        out += "\n";
      }
      if (a.found && a.evidence) out += `Evidence: "${a.evidence}"\n\n`;
      out += `Confidence: ${a.confidence}%\n${"-".repeat(60)}\n\n`;
    });
    const blob = new Blob([out], { type: "text/plain" });
    const url  = URL.createObjectURL(blob);
    const el   = document.createElement("a");
    el.href    = url;
    el.download = `${qName.replace(/\s+/g, "_")}_answers.txt`;
    el.click();
    URL.revokeObjectURL(url);
  };

  // ── Auth gate ─────────────────────────────────────────────────────────────
  if (!user) return (
    <div style={{ background: "var(--bg)", minHeight: "100vh" }}>
      <ParticleCanvas />
      <AuthScreen onLogin={setUser} />
    </div>
  );

  // ── Main shell ────────────────────────────────────────────────────────────
  if (!hydrated) {
    return (
      <div style={{ background: "var(--bg)", minHeight: "100vh", color: "var(--muted)", display: "grid", placeItems: "center" }}>
        Loading your workspace...
      </div>
    );
  }

  const logout = () => {
    localStorage.removeItem("medivault_user");
    setUser(null);
  };

  return (
    <div style={{ background: "var(--bg)", minHeight: "100vh", position: "relative" }}>
      <ParticleCanvas />

      {/* Header */}
      <header className="glass" style={{
        position: "sticky", top: 0, zIndex: 100, padding: "0 32px",
        display: "flex", alignItems: "center", justifyContent: "space-between",
        height: 58, borderBottom: "1px solid var(--border)", borderRadius: 0,
        boxShadow: "0 1px 40px rgba(0,0,0,0.4)",
      }}>
        <div style={{ display: "flex", alignItems: "center", gap: 28 }}>
          {/* Logo */}
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <div style={{
              width: 28, height: 28, borderRadius: 7,
              background: "linear-gradient(135deg, rgba(0,221,180,0.2), rgba(0,184,212,0.1))",
              border: "1px solid rgba(0,221,180,0.3)",
              display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14,
            }}>⬡</div>
            <span style={{ fontFamily: "var(--serif)", fontSize: 18, letterSpacing: "-0.01em", color: "var(--text)" }}>
              MediVault
            </span>
          </div>

          <div style={{ width: 1, height: 20, background: "var(--border)" }} />

          {/* Nav tabs */}
          <nav style={{ display: "flex", gap: 4 }}>
            {[
              { key: "upload",  label: "Setup" },
              { key: "answers", label: "Answers" + (answers.length ? ` (${answers.length})` : "") },
              { key: "export",  label: "Export" },
            ].map(t => (
              <button
                key={t.key}
                className={`tab-btn ${tab === t.key ? "active" : ""}`}
                onClick={() => setTab(t.key)}
              >
                {t.label}
              </button>
            ))}
          </nav>
        </div>

        {/* User + logout */}
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <span style={{ color: "var(--muted)", fontSize: 12, fontFamily: "var(--mono)" }}>
            {user.name || user.email}
          </span>
          <button
            onClick={logout}
            style={{
              background: "transparent", color: "var(--muted)", border: "1px solid var(--border)",
              borderRadius: 6, padding: "4px 12px", cursor: "pointer", fontSize: 11, fontFamily: "var(--mono)",
              transition: "all 0.15s",
            }}
            onMouseEnter={e => { e.target.style.color = "var(--red)"; e.target.style.borderColor = "rgba(255,91,107,0.3)"; }}
            onMouseLeave={e => { e.target.style.color = "var(--muted)"; e.target.style.borderColor = "var(--border)"; }}
          >
            logout
          </button>
        </div>
      </header>

      {/* Main content */}
      <main style={{ maxWidth: 860, margin: "0 auto", padding: "36px 24px", position: "relative", zIndex: 1 }}>

        {tab === "upload" && (
          <UploadTab
            documents={documents}
            setDocuments={setDocuments}
            qText={qText}
            setQText={setQText}
            qName={qName}
            setQName={setQName}
            generating={generating}
            onGenerate={generate}
          />
        )}

        {tab === "answers" && (
          <AnswersTab
            answers={answers}
            answered={answered}
            notFound={notFound}
            avgConf={avgConf}
            generating={generating}
            progress={progress}
            qName={qName}
            onEdit={editAnswer}
            onExport={() => setTab("export")}
          />
        )}

        {tab === "export" && (
          <ExportTab
            answers={answers}
            answered={answered}
            notFound={notFound}
            avgConf={avgConf}
            qName={qName}
            onDownload={exportDoc}
            onSetupClick={() => setTab("upload")}
          />
        )}
      </main>
    </div>
  );
}
